services:
  - type: web
    name: formatura-leo
    env: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: EVENT_GRADUATE_NAME
        value: "Leonardo Brzezinski Caparica de Almeida"
      - key: EVENT_CEREMONY_DATE
        value: "16/02/2027"
      - key: EVENT_BALL_DATE
        value: "20/02/2027"
      - key: EVENT_LOCATION
        value: "Centro de Eventos Cidade dos Lagos, Guarapuava-PR"
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
